language: objective-c
osx_image: xcode9
script:
    - brew install curl cmake
    - brew install uncrustify glfw3 emscripten
    - python emsetup.py
    - cmake -DHAVE_FUNTIMENS=0 -DEMSCRIPTEN=ON . -Bbuild
    - cmake --build build
